/**
 * _worker.js  — Cloudflare Pages Advanced Mode entry point
 *
 * This file is auto-generated by `node build.js` (via esbuild).
 * It wraps the Express app with Cloudflare's Node.js compat httpServerHandler.
 *
 * Requires: compatibility_flags = ["nodejs_compat"] in wrangler.toml
 */

'use strict';

const { httpServerHandler } = require('cloudflare:node');
const app = require('./server');

// Export the Cloudflare Pages / Workers fetch handler
module.exports = {
  fetch: httpServerHandler(app),
};
